sudo: required
services:
  - docker

before_install:
  - docker build -t pradsi/docker-react -f Dockerfile.dev .

script:
 # - docker run pradsi/docker-react npm run test -- --coverage
 - docker run -e CI=true pradsi/docker-react npm run test
